addSbtPlugin("io.get-coursier"		% "sbt-coursier"				% "1.0.3")
addSbtPlugin("io.spray"				% "sbt-boilerplate"				% "0.6.1")
addSbtPlugin("org.wartremover"		% "sbt-wartremover" 			% "2.4.2")
addSbtPlugin("org.portable-scala"	% "sbt-scalajs-crossproject"	% "0.6.0")
addSbtPlugin("org.scala-js"			% "sbt-scalajs"					% "0.6.27")
